name: Usable Workflow
on:
    workflow_dispatch:
      inputs:
        title:
              description: "Custom title"
              type: string
              default: "Testing text title"
              required: true

jobs:
  call_local_workflow:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      title: ${{ inputs.title }}
  call_external_workflow:
    uses: OPshenichnyi/workflows/.github/workflows/workflow.yml@main
    with: {}
    secrets: 
      PASSWORD: ${{ secrets.PASSWORD_SECRET_ONE }}