name: Usable Workflow
on:
    workflow_dispatch:
      inputs:
        title:
              description: "Custom title"
              type: string
              default: "Testing text title"
              required: true

jobs:
  workflow_call:
       uses: ./.github/workflows/reusable_workflow.yml
       with:
          title: ${{ inputs.title }}